Repository MalteMagnussen/CA2-FrontEnd, pull requests merged in 2019-10, with the labels that each got.

#24 Tiny setup-PR
  .travis.yml
  public/index.html
  src/index.js
  src/jokes.js
Labels: Sprint 3

#26 Issue#12 add person simple
  public/index.html
  src/addPersonSimple.js
  src/index.js
Labels: Sprint 3

#27 Issue #5 View person with data
  public/index.html
  src/index.js
Labels: Sprint 3

#32 Layout
  public/index.html
Labels: Sprint 3

#30 Sort Persons Util Method.
  src/index.js
Labels: Sprint 3

#31 Scrum Page moved from Backend Repo
  public/index.html
Labels: Sprint 3

#33 Show all users in both table and p-tag
  public/index.html
  src/index.js
Labels: Sprint 3

#35 Get hobby by name & get persons by hobby
  public/index.html
  src/index.js
Labels: Sprint 3

#38 BugFix
  src/index.js
Labels: Sprint 3, bug

#34 Dynamic Navigation
  public/add.html
  public/get.html
  public/home.html
  public/index.html
  public/scrum.html
  public/style.css
  src/index.js
Labels: DON'T MERGE YET, Sprint 3

#41 Javascript has been moved.
  public/add.html
  public/get.html
  public/index.html
  src/index.js
Labels: Sprint 3

#49 Fix of undefined cells in tables
  src/index.js
Labels: Sprint 3, bug

#51 Styling done
  public/add.html
  public/get.html
  public/home.html
  public/index.html
  public/style.css
  src/index.js
Labels: Sprint 3

#55 Issue#22 create all
  public/add.html
  public/get.html
  public/index.html
  public/style.css
  src/addPersonSimple.js
  src/index.js
Labels: MUST BE DONE BEFORE SUNDAY NIGHT, Sprint 3

#60 Implemented editHobby feature
  public/get.html
  public/style.css
  src/index.js
Labels: Sprint 3

#50 Implement deletePerson
  public/scrum.html
  public/style.css
  src/index.js
Labels: Sprint 3
